version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.6
    container_name: shopdev_es
    environment:
      - node.name=shopdev_es
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.6
    container_name: shopdev_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://shopdev_es:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - es-net

volumes:
  esdata:
    driver: local

networks:
  es-net:
    driver: bridge
